package game.gameControl

enum class GameState {
    MONSTER_CHOOSING,
    STEP_SPINNER_SPINNING,
    STEP_SPINNER_SPINNED,
    STEPPING,
    BATTLE_SPINNER_SPINNING,
    BATTLE_SPINNER_SPINNED,
    BATTLE,
    ESCAPE_SPINNER_SPINNING,
    ESCAPE_SPINNER_SPINNED,
    ESCAPE,
    TURN_FINISH,
}
